### ISSUE TITLE
Product

### ISSUE THREAD

**Issue by namgh** [spharos-clone-6/backend#12]
## 💬 Description

개발할 상세 기능을 적어 주세요
addProduct
getProduct
getAllProduct
addProductCategory
getProductById
getProductByCategory_Category

## ✅ To Do

- [x]  addProduct
- [x]  getProduct
- [x]  getAllProduct
- [x] addProductCategory
- [x] getProductById
- [x] getProductByCategory_Category

**Comment by Junseokee** [comment]
오늘부로 모두 완료했습니다.
